### ISSUE TITLE
change background colors of all divs on page

### ISSUE THREAD

**Issue by kmvpvl** [SebastianSushi/exer#8]
1) add to Menu new button "CHANGE COLOR..."
2) add to Menu new input color picker
3) on button "CHANGE COLOR..." click change background color of all divs on page

**Comment by abitsalihu** [comment]
Hey @kmvpvl, I would like to help with this issue. :)

**Comment by SebastianSushi** [comment]
> Hey @kmvpvl, I would like to help with this issue. :)

Аctually this is my training, so its my exercise for tomorrow. I have to do it myself, thanks for the offer ;)

**Comment by abitsalihu** [comment]
Oh okay, good luck on it. :)

**Comment by SebastianSushi** [comment]
done
